import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Tree,
  TreeChildren,
  TreeParent,
} from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';

@Entity()
@Tree('materialized-path')
export class Menu {
  @ApiProperty({ description: '菜单ID' })
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ApiProperty({ description: '父菜单ID', required: false })
  @Column({ nullable: true })
  parentId?: string;

  @ApiProperty({ description: '菜单路径' })
  @Column()
  path: string;

  @ApiProperty({ description: '菜单名称' })
  @Column()
  name: string;

  @ApiProperty({ description: '组件路径', required: false })
  @Column({ nullable: true })
  component?: string;

  @ApiProperty({ description: '重定向路径', required: false })
  @Column({ nullable: true })
  redirect?: string;

  @ApiProperty({ description: '菜单标题', required: false })
  @Column({ nullable: true })
  metaTitle?: string;

  @ApiProperty({ description: '菜单图标', required: false })
  @Column({ nullable: true })
  metaIcon?: string;

  @ApiProperty({ description: '是否隐藏菜单' })
  @Column({ default: false })
  metaHidden: boolean;

  @ApiProperty({ description: '是否始终显示' })
  @Column({ default: false })
  metaAlwaysShow: boolean;

  @ApiProperty({ description: '排序序号' })
  @Column({ default: 0 })
  sortOrder: number;

  @ApiProperty({ description: '菜单状态', enum: ['active', 'inactive'] })
  @Column({ default: 'active' })
  status: string;

  @ApiProperty({ description: '自动生成的权限', required: false })
  @Column({ nullable: true })
  autoGeneratedPermission?: string;

  @TreeChildren()
  children: Menu[];

  @TreeParent()
  parent: Menu;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
