/**
 * 错误码常量
 * 定义系统中使用的错误码
 * 采用分段编码体系：
 * 1000-1999: 通用错误
 * 2000-2999: 认证相关错误
 * 3000-3999: 用户相关错误
 * 4000-4999: 权限相关错误
 * 5000-5999: 角色相关错误
 * 6000-6999: 菜单相关错误
 * 7000-7999: 物料相关错误
 * 8000-8999: 分类相关错误
 * 9000-9999: 业务相关错误
 */

export const ERROR_CODES = {
  // 成功
  SUCCESS: 200,

  // 通用错误 (1000-1999)
  INTERNAL_SERVER_ERROR: 1000,
  INVALID_PARAMETER: 1001,
  VALIDATION_ERROR: 1002,
  RESOURCE_NOT_FOUND: 1003,
  RESOURCE_ALREADY_EXISTS: 1004,
  OPERATION_FAILED: 1005,
  DATABASE_ERROR: 1006,
  NETWORK_ERROR: 1007,
  SERVICE_UNAVAILABLE: 1008,
  TIMEOUT_ERROR: 1009,

  // 认证相关错误 (2000-2999)
  UNAUTHORIZED: 2000,
  INVALID_TOKEN: 2001,
  TOKEN_EXPIRED: 2002,
  INVALID_CREDENTIALS: 2003,
  ACCOUNT_LOCKED: 2004,
  ACCOUNT_DISABLED: 2005,
  LOGIN_REQUIRED: 2006,
  SESSION_EXPIRED: 2007,
  INVALID_REFRESH_TOKEN: 2008,
  AUTH_TOKEN_INVALID: 2009,
  AUTH_USER_INFO_MISSING: 2010,
  AUTH_INVALID_CREDENTIALS: 2011,
  AUTH_LOGIN_FAILED: 2012,
  AUTH_PASSWORD_MISMATCH: 2013,

  // 用户相关错误 (3000-3999)
  USER_NOT_FOUND: 3000,
  USER_ALREADY_EXISTS: 3001,
  USER_DISABLED: 3002,
  USER_LOCKED: 3003,
  INVALID_USER_DATA: 3004,
  USER_UPDATE_FAILED: 3005,
  USER_DELETE_FAILED: 3006,
  USER_CREATE_FAILED: 3007,
  USER_PASSWORD_INVALID: 3008,
  USER_EMAIL_EXISTS: 3009,
  USER_PHONE_EXISTS: 3010,
  USER_ID_UNDEFINED: 3011,
  INVALID_USER_ID: 3012,
  INVALID_PASSWORD: 3013,
  PASSWORD_SAME_AS_CURRENT: 3014,
  USER_INFO_RETRIEVAL_FAILED: 3015,

  // 权限相关错误 (4000-4999)
  FORBIDDEN: 4000,
  INSUFFICIENT_PERMISSIONS: 4001,
  PERMISSION_DENIED: 4002,
  ACCESS_DENIED: 4003,
  OPERATION_NOT_ALLOWED: 4004,
  PERMISSION_ROLE_INSUFFICIENT: 4005,
  PERMISSION_INSUFFICIENT: 4006,
  PERMISSION_ALREADY_EXISTS: 4007,
  PERMISSION_NOT_FOUND: 4008,

  // 角色相关错误 (5000-5999)
  ROLE_NOT_FOUND: 5000,
  ROLE_ALREADY_EXISTS: 5001,
  ROLE_IN_USE: 5002,
  ROLE_UPDATE_FAILED: 5003,
  ROLE_DELETE_FAILED: 5004,
  INVALID_ROLE_DATA: 5005,
  SYSTEM_ROLE_IMMUTABLE: 5006,
  ROLE_TYPE_IMMUTABLE: 5007,
  INVALID_ROLE_TYPE: 5008,

  // 菜单相关错误 (6000-6999)
  MENU_NOT_FOUND: 6000,
  MENU_ALREADY_EXISTS: 6001,
  MENU_UPDATE_FAILED: 6002,
  MENU_DELETE_FAILED: 6003,
  INVALID_MENU_DATA: 6004,
  MENU_HAS_CHILDREN: 6005,

  // 物料相关错误 (7000-7999)
  MATERIAL_NOT_FOUND: 7000,
  MATERIAL_ALREADY_EXISTS: 7001,
  MATERIAL_UPDATE_FAILED: 7002,
  MATERIAL_DELETE_FAILED: 7003,
  INVALID_MATERIAL_DATA: 7004,
  MATERIAL_INSUFFICIENT: 7005,
  MATERIAL_CATEGORY_INVALID: 7006,

  // 分类相关错误 (8000-8999)
  CATEGORY_NOT_FOUND: 8000,
  CATEGORY_ALREADY_EXISTS: 8001,
  CATEGORY_UPDATE_FAILED: 8002,
  CATEGORY_DELETE_FAILED: 8003,
  INVALID_CATEGORY_DATA: 8004,
  CATEGORY_HAS_CHILDREN: 8005,
  CATEGORY_HAS_MATERIALS: 8006,
  CATEGORY_CANNOT_MOVE_TO_SELF: 8007,

  // 业务相关错误 (9000-9999)
  BUSINESS_VALIDATION_ERROR: 9000,
  BUSINESS_LOGIC_ERROR: 9001,
  CONCURRENT_MODIFICATION: 9002,
  DUPLICATE_OPERATION: 9003,
  LIMIT_EXCEEDED: 9004,
  QUOTA_EXCEEDED: 9005,
  VALIDATION_INVALID_ID: 9006,
  VALIDATION_FAILED: 9007,
} as const;

/**
 * 错误消息映射
 */
export const ERROR_MESSAGES = {
  [ERROR_CODES.SUCCESS]: '操作成功',

  // 通用错误
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: '服务器内部错误',
  [ERROR_CODES.INVALID_PARAMETER]: '参数无效',
  [ERROR_CODES.VALIDATION_ERROR]: '数据验证失败',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: '资源不存在',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: '资源已存在',
  [ERROR_CODES.OPERATION_FAILED]: '操作失败',
  [ERROR_CODES.DATABASE_ERROR]: '数据库错误',
  [ERROR_CODES.NETWORK_ERROR]: '网络错误',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: '服务不可用',
  [ERROR_CODES.TIMEOUT_ERROR]: '请求超时',

  // 认证相关
  [ERROR_CODES.UNAUTHORIZED]: '未授权访问',
  [ERROR_CODES.INVALID_TOKEN]: '无效的令牌',
  [ERROR_CODES.TOKEN_EXPIRED]: '令牌已过期',
  [ERROR_CODES.INVALID_CREDENTIALS]: '用户名或密码错误',
  [ERROR_CODES.ACCOUNT_LOCKED]: '账户已被锁定',
  [ERROR_CODES.ACCOUNT_DISABLED]: '账户已被禁用',
  [ERROR_CODES.LOGIN_REQUIRED]: '需要登录',
  [ERROR_CODES.SESSION_EXPIRED]: '会话已过期',
  [ERROR_CODES.INVALID_REFRESH_TOKEN]: '无效的刷新令牌',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: '认证令牌无效',
  [ERROR_CODES.AUTH_USER_INFO_MISSING]: '用户认证信息缺失',
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: '认证凭据无效',
  [ERROR_CODES.AUTH_LOGIN_FAILED]: '登录失败',
  [ERROR_CODES.AUTH_PASSWORD_MISMATCH]: '密码不匹配',

  // 用户相关
  [ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODES.USER_ALREADY_EXISTS]: '用户已存在',
  [ERROR_CODES.USER_DISABLED]: '用户已被禁用',
  [ERROR_CODES.USER_LOCKED]: '用户已被锁定',
  [ERROR_CODES.INVALID_USER_DATA]: '用户数据无效',
  [ERROR_CODES.USER_UPDATE_FAILED]: '用户更新失败',
  [ERROR_CODES.USER_DELETE_FAILED]: '用户删除失败',
  [ERROR_CODES.USER_CREATE_FAILED]: '用户创建失败',
  [ERROR_CODES.USER_PASSWORD_INVALID]: '用户密码无效',
  [ERROR_CODES.USER_EMAIL_EXISTS]: '邮箱已存在',
  [ERROR_CODES.USER_PHONE_EXISTS]: '手机号已存在',
  [ERROR_CODES.USER_ID_UNDEFINED]: '用户ID未定义',
  [ERROR_CODES.INVALID_USER_ID]: '无效的用户ID',
  [ERROR_CODES.INVALID_PASSWORD]: '无效的密码',
  [ERROR_CODES.PASSWORD_SAME_AS_CURRENT]: '新密码不能与当前密码相同',
  [ERROR_CODES.USER_INFO_RETRIEVAL_FAILED]: '获取用户信息失败',

  // 权限相关
  [ERROR_CODES.FORBIDDEN]: '禁止访问',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: '权限不足',
  [ERROR_CODES.PERMISSION_DENIED]: '权限被拒绝',
  [ERROR_CODES.ACCESS_DENIED]: '访问被拒绝',
  [ERROR_CODES.OPERATION_NOT_ALLOWED]: '操作不允许',
  [ERROR_CODES.PERMISSION_ROLE_INSUFFICIENT]: '角色权限不足',
  [ERROR_CODES.PERMISSION_INSUFFICIENT]: '权限不足',
  [ERROR_CODES.PERMISSION_ALREADY_EXISTS]: '权限已存在',
  [ERROR_CODES.PERMISSION_NOT_FOUND]: '权限不存在',

  // 角色相关
  [ERROR_CODES.ROLE_NOT_FOUND]: '角色不存在',
  [ERROR_CODES.ROLE_ALREADY_EXISTS]: '角色已存在',
  [ERROR_CODES.ROLE_IN_USE]: '角色正在使用中',
  [ERROR_CODES.ROLE_UPDATE_FAILED]: '角色更新失败',
  [ERROR_CODES.ROLE_DELETE_FAILED]: '角色删除失败',
  [ERROR_CODES.INVALID_ROLE_DATA]: '角色数据无效',
  [ERROR_CODES.SYSTEM_ROLE_IMMUTABLE]: '系统角色不可修改',
  [ERROR_CODES.ROLE_TYPE_IMMUTABLE]: '角色类型不可修改',
  [ERROR_CODES.INVALID_ROLE_TYPE]: '无效的角色类型',

  // 菜单相关
  [ERROR_CODES.MENU_NOT_FOUND]: '菜单不存在',
  [ERROR_CODES.MENU_ALREADY_EXISTS]: '菜单已存在',
  [ERROR_CODES.MENU_UPDATE_FAILED]: '菜单更新失败',
  [ERROR_CODES.MENU_DELETE_FAILED]: '菜单删除失败',
  [ERROR_CODES.INVALID_MENU_DATA]: '菜单数据无效',
  [ERROR_CODES.MENU_HAS_CHILDREN]: '菜单包含子菜单',

  // 物料相关
  [ERROR_CODES.MATERIAL_NOT_FOUND]: '物料不存在',
  [ERROR_CODES.MATERIAL_ALREADY_EXISTS]: '物料已存在',
  [ERROR_CODES.MATERIAL_UPDATE_FAILED]: '物料更新失败',
  [ERROR_CODES.MATERIAL_DELETE_FAILED]: '物料删除失败',
  [ERROR_CODES.INVALID_MATERIAL_DATA]: '物料数据无效',
  [ERROR_CODES.MATERIAL_INSUFFICIENT]: '物料库存不足',
  [ERROR_CODES.MATERIAL_CATEGORY_INVALID]: '物料分类无效',

  // 分类相关
  [ERROR_CODES.CATEGORY_NOT_FOUND]: '分类不存在',
  [ERROR_CODES.CATEGORY_ALREADY_EXISTS]: '分类已存在',
  [ERROR_CODES.CATEGORY_UPDATE_FAILED]: '分类更新失败',
  [ERROR_CODES.CATEGORY_DELETE_FAILED]: '分类删除失败',
  [ERROR_CODES.INVALID_CATEGORY_DATA]: '分类数据无效',
  [ERROR_CODES.CATEGORY_HAS_CHILDREN]: '分类包含子分类',
  [ERROR_CODES.CATEGORY_HAS_MATERIALS]: '分类包含物料',
  [ERROR_CODES.CATEGORY_CANNOT_MOVE_TO_SELF]: '不能将分类移动到自己的子分类下',

  // 业务相关
  [ERROR_CODES.BUSINESS_VALIDATION_ERROR]: '业务验证失败',
  [ERROR_CODES.BUSINESS_LOGIC_ERROR]: '业务逻辑错误',
  [ERROR_CODES.CONCURRENT_MODIFICATION]: '并发修改冲突',
  [ERROR_CODES.DUPLICATE_OPERATION]: '重复操作',
  [ERROR_CODES.LIMIT_EXCEEDED]: '超出限制',
  [ERROR_CODES.QUOTA_EXCEEDED]: '超出配额',
  [ERROR_CODES.VALIDATION_INVALID_ID]: 'ID验证失败',
  [ERROR_CODES.VALIDATION_FAILED]: '数据验证失败',
} as const;

/**
 * 错误码与HTTP状态码映射
 */
export const ERROR_TO_HTTP_STATUS = {
  [ERROR_CODES.SUCCESS]: 200,

  // 通用错误映射
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODES.INVALID_PARAMETER]: 400,
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 409,
  [ERROR_CODES.OPERATION_FAILED]: 500,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.NETWORK_ERROR]: 503,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.TIMEOUT_ERROR]: 408,

  // 认证相关映射
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.INVALID_TOKEN]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.ACCOUNT_LOCKED]: 401,
  [ERROR_CODES.ACCOUNT_DISABLED]: 401,
  [ERROR_CODES.LOGIN_REQUIRED]: 401,
  [ERROR_CODES.SESSION_EXPIRED]: 401,
  [ERROR_CODES.INVALID_REFRESH_TOKEN]: 401,
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 401,
  [ERROR_CODES.AUTH_USER_INFO_MISSING]: 401,
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.AUTH_LOGIN_FAILED]: 401,
  [ERROR_CODES.AUTH_PASSWORD_MISMATCH]: 400,

  // 用户相关映射
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
  [ERROR_CODES.USER_DISABLED]: 403,
  [ERROR_CODES.USER_LOCKED]: 403,
  [ERROR_CODES.INVALID_USER_DATA]: 400,
  [ERROR_CODES.USER_UPDATE_FAILED]: 500,
  [ERROR_CODES.USER_DELETE_FAILED]: 500,
  [ERROR_CODES.USER_CREATE_FAILED]: 500,
  [ERROR_CODES.USER_PASSWORD_INVALID]: 400,
  [ERROR_CODES.USER_EMAIL_EXISTS]: 409,
  [ERROR_CODES.USER_PHONE_EXISTS]: 409,
  [ERROR_CODES.USER_ID_UNDEFINED]: 400,
  [ERROR_CODES.INVALID_USER_ID]: 400,
  [ERROR_CODES.INVALID_PASSWORD]: 400,
  [ERROR_CODES.PASSWORD_SAME_AS_CURRENT]: 400,

  // 权限相关映射
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,
  [ERROR_CODES.PERMISSION_DENIED]: 403,
  [ERROR_CODES.ACCESS_DENIED]: 403,
  [ERROR_CODES.OPERATION_NOT_ALLOWED]: 403,
  [ERROR_CODES.PERMISSION_ROLE_INSUFFICIENT]: 403,
  [ERROR_CODES.PERMISSION_INSUFFICIENT]: 403,
  [ERROR_CODES.PERMISSION_ALREADY_EXISTS]: 409,
  [ERROR_CODES.PERMISSION_NOT_FOUND]: 404,

  [ERROR_CODES.SYSTEM_ROLE_IMMUTABLE]: 403,
  [ERROR_CODES.ROLE_TYPE_IMMUTABLE]: 403,
  [ERROR_CODES.CATEGORY_CANNOT_MOVE_TO_SELF]: 400,
  [ERROR_CODES.VALIDATION_INVALID_ID]: 400,
  [ERROR_CODES.VALIDATION_FAILED]: 400,

  // 其他错误映射到400或500
} as const;
