/**
 * 错误码常量
 * 定义系统中使用的错误码
 * 采用分段编码体系：
 * 1000-1999: 通用错误
 * 2000-2999: 认证相关错误
 * 3000-3999: 用户相关错误
 * 4000-4999: 权限相关错误
 * 5000-5999: 角色相关错误
 * 6000-6999: 菜单相关错误
 * 7000-7999: 物料相关错误
 * 8000-8999: 分类相关错误
 * 9000-9999: 业务相关错误
 */

export const ERROR_CODES = {
  // 成功
  SUCCESS: 200,

  // 认证相关错误 (2000-2999)
  INVALID_TOKEN: 2001,
  ACCOUNT_LOCKED: 2004,
  ACCOUNT_DISABLED: 2005,
  AUTH_TOKEN_INVALID: 2009,
  AUTH_USER_INFO_MISSING: 2010,
  AUTH_INVALID_CREDENTIALS: 2011,
  AUTH_LOGIN_FAILED: 2012,
  AUTH_PASSWORD_MISMATCH: 2013,

  // 用户相关错误 (3000-3999)
  USER_NOT_FOUND: 3000,
  USER_ALREADY_EXISTS: 3001,
  USER_ID_UNDEFINED: 3011,
  INVALID_USER_ID: 3012,
  INVALID_PASSWORD: 3013,
  PASSWORD_SAME_AS_CURRENT: 3014,
  USER_INFO_RETRIEVAL_FAILED: 3015,

  // 权限相关错误 (4000-4999)
  PERMISSION_ROLE_INSUFFICIENT: 4005,
  PERMISSION_INSUFFICIENT: 4006,
  PERMISSION_ALREADY_EXISTS: 4007,
  PERMISSION_NOT_FOUND: 4008,

  // 角色相关错误 (5000-5999)
  ROLE_NOT_FOUND: 5000,

  // 菜单相关错误 (6000-6999)
  MENU_NOT_FOUND: 6000,

  // 物料相关错误 (7000-7999)
  MATERIAL_NOT_FOUND: 7000,
  MATERIAL_ALREADY_EXISTS: 7001,
  MATERIAL_IS_ON_SHELF: 7002,

  // 分类相关错误 (8000-8999)
  CATEGORY_NOT_FOUND: 8000,
  CATEGORY_ALREADY_EXISTS: 8001,
  CATEGORY_HAS_CHILDREN: 8005,
  CATEGORY_HAS_MATERIALS: 8006,
  CATEGORY_CANNOT_MOVE_TO_SELF: 8007,

  // 库存相关错误 (8100-8199)
  INVENTORY_NOT_FOUND: 8100,
  INSUFFICIENT_STOCK: 8101,
  INVALID_OPERATION: 8102,

  // 文件上传相关错误 (8500-8599)
  UPLOAD_FAILED: 8500,
  FILE_REQUIRED: 8501,
  INVALID_FILE_TYPE: 8502,
  FILE_TOO_LARGE: 8503,
  TOO_MANY_FILES: 8504,
  IMAGE_NOT_FOUND: 8505,
  INVALID_IMAGE_MATERIAL: 8506,

  // 业务相关错误 (9000-9999)
  VALIDATION_INVALID_ID: 9006,
  VALIDATION_FAILED: 9007,
} as const;

/**
 * 错误消息映射
 */
export const ERROR_MESSAGES = {
  [ERROR_CODES.SUCCESS]: '操作成功',

  // 认证相关
  [ERROR_CODES.INVALID_TOKEN]: '认证令牌无效',
  [ERROR_CODES.ACCOUNT_LOCKED]: '账户已被锁定，请联系管理员',
  [ERROR_CODES.ACCOUNT_DISABLED]: '账户已被禁用，请联系管理员',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: '认证令牌无效或已过期',
  [ERROR_CODES.AUTH_USER_INFO_MISSING]: '用户认证信息缺失',
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: '账号或密码错误',
  [ERROR_CODES.AUTH_LOGIN_FAILED]: '登录失败，请稍后重试',
  [ERROR_CODES.AUTH_PASSWORD_MISMATCH]: '账号或密码错误',

  // 用户相关
  [ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODES.USER_ALREADY_EXISTS]: '用户已存在',
  [ERROR_CODES.USER_ID_UNDEFINED]: '用户ID未定义',
  [ERROR_CODES.INVALID_USER_ID]: '无效的用户ID',
  [ERROR_CODES.INVALID_PASSWORD]: '无效的密码',
  [ERROR_CODES.PASSWORD_SAME_AS_CURRENT]: '新密码不能与当前密码相同',
  [ERROR_CODES.USER_INFO_RETRIEVAL_FAILED]: '获取用户信息失败',

  // 权限相关
  [ERROR_CODES.PERMISSION_ROLE_INSUFFICIENT]: '角色权限不足',
  [ERROR_CODES.PERMISSION_INSUFFICIENT]: '权限不足',
  [ERROR_CODES.PERMISSION_ALREADY_EXISTS]: '权限已存在',
  [ERROR_CODES.PERMISSION_NOT_FOUND]: '权限不存在',

  // 角色相关
  [ERROR_CODES.ROLE_NOT_FOUND]: '角色不存在',

  // 菜单相关
  [ERROR_CODES.MENU_NOT_FOUND]: '菜单不存在',

  // 物料相关
  [ERROR_CODES.MATERIAL_NOT_FOUND]: '物料不存在',
  [ERROR_CODES.MATERIAL_ALREADY_EXISTS]: '物料已存在',
  [ERROR_CODES.MATERIAL_IS_ON_SHELF]: '该素材已上架，无法删除',

  // 分类相关
  [ERROR_CODES.CATEGORY_NOT_FOUND]: '分类不存在',
  [ERROR_CODES.CATEGORY_ALREADY_EXISTS]: '分类已存在',
  [ERROR_CODES.CATEGORY_HAS_CHILDREN]: '分类包含子分类',
  [ERROR_CODES.CATEGORY_HAS_MATERIALS]: '分类包含物料',
  [ERROR_CODES.CATEGORY_CANNOT_MOVE_TO_SELF]: '不能将分类移动到自己的子分类下',

  // 库存相关
  [ERROR_CODES.INVENTORY_NOT_FOUND]: '库存记录不存在',
  [ERROR_CODES.INSUFFICIENT_STOCK]: '库存不足',
  [ERROR_CODES.INVALID_OPERATION]: '无效的操作类型',

  // 业务相关
  [ERROR_CODES.VALIDATION_INVALID_ID]: 'ID验证失败',
  [ERROR_CODES.VALIDATION_FAILED]: '数据验证失败',
} as const;

/**
 * 错误码与HTTP状态码映射
 */
// export const ERROR_TO_HTTP_STATUS = {
//   [ERROR_CODES.SUCCESS]: 200,

//   // 认证相关映射
//   [ERROR_CODES.INVALID_TOKEN]: 401,
//   [ERROR_CODES.ACCOUNT_LOCKED]: 401,
//   [ERROR_CODES.ACCOUNT_DISABLED]: 401,
//   [ERROR_CODES.AUTH_TOKEN_INVALID]: 401,
//   [ERROR_CODES.AUTH_USER_INFO_MISSING]: 401,
//   [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 401,
//   [ERROR_CODES.AUTH_LOGIN_FAILED]: 401,
//   [ERROR_CODES.AUTH_PASSWORD_MISMATCH]: 400,

//   // 用户相关映射
//   [ERROR_CODES.USER_NOT_FOUND]: 404,
//   [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
//   [ERROR_CODES.USER_ID_UNDEFINED]: 400,
//   [ERROR_CODES.INVALID_USER_ID]: 400,
//   [ERROR_CODES.INVALID_PASSWORD]: 400,
//   [ERROR_CODES.PASSWORD_SAME_AS_CURRENT]: 400,

//   // 权限相关映射
//   [ERROR_CODES.PERMISSION_ROLE_INSUFFICIENT]: 403,
//   [ERROR_CODES.PERMISSION_INSUFFICIENT]: 403,
//   [ERROR_CODES.PERMISSION_ALREADY_EXISTS]: 409,
//   [ERROR_CODES.PERMISSION_NOT_FOUND]: 404,

//   // 角色相关映射
//   [ERROR_CODES.ROLE_NOT_FOUND]: 404,

//   // 菜单相关映射
//   [ERROR_CODES.MENU_NOT_FOUND]: 404,

//   // 物料相关映射
//   [ERROR_CODES.MATERIAL_NOT_FOUND]: 404,
//   [ERROR_CODES.MATERIAL_ALREADY_EXISTS]: 409,

//   // 分类相关映射
//   [ERROR_CODES.CATEGORY_NOT_FOUND]: 404,
//   [ERROR_CODES.CATEGORY_ALREADY_EXISTS]: 409,
//   [ERROR_CODES.CATEGORY_HAS_CHILDREN]: 400,
//   [ERROR_CODES.CATEGORY_HAS_MATERIALS]: 400,
//   [ERROR_CODES.CATEGORY_CANNOT_MOVE_TO_SELF]: 400,

//   // 业务相关映射
//   [ERROR_CODES.VALIDATION_INVALID_ID]: 400,
//   [ERROR_CODES.VALIDATION_FAILED]: 400,
// } as const;
