/**
 * 错误码常量
 * 定义系统中使用的错误码
 */
export const ERROR_CODES = {
  // 成功
  SUCCESS: 200,

  // 通用错误 (1000-1999)
  INTERNAL_SERVER_ERROR: 1000,
  INVALID_PARAMETER: 1001,
  VALIDATION_ERROR: 1002,

  // 认证相关错误 (2000-2999)
  UNAUTHORIZED: 2000,
  INVALID_TOKEN: 2001,
  TOKEN_EXPIRED: 2002,
  INVALID_CREDENTIALS: 2003,

  // 用户相关错误 (3000-3999)
  USER_NOT_FOUND: 3000,
  USER_ALREADY_EXISTS: 3001,
  USER_DISABLED: 3002,

  // 权限相关错误 (4000-4999)
  FORBIDDEN: 4000,
  INSUFFICIENT_PERMISSIONS: 4001,
} as const;

/**
 * 错误消息映射
 */
export const ERROR_MESSAGES = {
  [ERROR_CODES.SUCCESS]: '操作成功',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: '服务器内部错误',
  [ERROR_CODES.INVALID_PARAMETER]: '参数无效',
  [ERROR_CODES.VALIDATION_ERROR]: '数据验证失败',
  [ERROR_CODES.UNAUTHORIZED]: '未授权访问',
  [ERROR_CODES.INVALID_TOKEN]: '无效的令牌',
  [ERROR_CODES.TOKEN_EXPIRED]: '令牌已过期',
  [ERROR_CODES.INVALID_CREDENTIALS]: '用户名或密码错误',
  [ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODES.USER_ALREADY_EXISTS]: '用户已存在',
  [ERROR_CODES.USER_DISABLED]: '用户已被禁用',
  [ERROR_CODES.FORBIDDEN]: '禁止访问',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: '权限不足',
} as const;
